target-version = "py312"

extend-include = ["*.ipynb"]

line-length = 120

[lint]
select = ["ALL"]
ignore = [
    # -- Must have --
    "D100",
    "D401",   # First line should be in imperative mood
    "D105",   # Function doc for every function
    "S101",
    "INP001", # __init__ for implicit namespace
    "T201",   # No print,
    "E501",   # Line too long
    "EXE002", # Use explicit exception handling
    "ANN401", # No Any type
    "COM812",
    "PGH003", # Error ignore

    # About TODO
    "TD002",
    "TD003",
    "FIX002",

    # Errors
    "BLE001",
    "EM102",  # Use error msg string not variable

    # -- Optional --
    "N803",    # Lower case parameter name
    "EM101",
    "TRY003",
    "PLR2004", # Use variable as parameter not constant
    "D106",    # Docstring is missing
    "D101",    # Missing docstring in public class
    "TC002",   # Use type hints
    "W293",    # No blank space line
    "ERA001",  # No comment
    "T203",    # No pprint
    "DTZ005",  # Use timezone aware datetime
    "D212",    # func doc string strains
    "FBT001",
    "FBT002",
    "N999",    # No snake_name check
]

[format]
docstring-code-format = true

[lint.per-file-ignores]
"src/**/*.ipynb" = ["D103"]
